### PR TITLE
Lots of features :)

### PR DESCRIPTION
**Pull request by Shuunen**
Hi @sazarkin :slightly_smiling_face: 

First thanks a lot for your zoom work on @marcincichocki original library :+1: 

The first thing I done on my side was to update the project to the latest vue-cli stack.

Then I added these features : 
* mouse wheel to scroll
* right click to toggle the upper photo
* middle click to toggle multiple times fastly
* drop file(s) ability to change the compared photos on the go
* photo name display

Let me know what do you think :smile:

### CODE REVIEW

**Comment by sazarkin** [comment]
Well, I never expected this fork to get pull requests :)
This is a lot of changes, I'll try to look into it, if original repo is not very active.

**Comment by Shuunen** [comment]
> Well, I never expected this fork to get pull requests :)

I see what you mean :p but I was wondering that maybe you'll be glad to have more features

> This is a lot of changes

Yep, I personally needed these to compare various image compression algorithm/settings precisely

> I'll try to look into it, if original repo is not very active.

Yea the original repo had no activity for a while

**Comment by ctf0** [comment]
@sazarkin any news, also are u planning to publish it ?

**Comment by Shuunen** [comment]
Since @ctf0 & I changed a lot of stuff, and no one is responding to PR for months now, https://github.com/Shuunen/vue-image-compare became **vue-image-compare2**

Thanks anyway for your work on this fork @sazarkin 👍

**Pull request closed without merging**
